### ISSUE TITLE
Drag and Drop Down Not Working

### ISSUE THREAD

**Issue by NathanielCoxson** [NathanielCoxson/To-Do-List-App#25]
Dragging a task down and trying to place it below another is not working as expected when there are more than two tasks in the panel. When there are three tasks present and you attempt to place the top one in the middle it will instead be placed at the bottom of the panel.

Since moving up one at a time seems to be working fine, I would assume that the issue is within the function in board that is moving the tasks around, somehow it is moving them down one further than they are supposed to go.

**Comment by SugatoBagchi** [comment]
Hi, I would like to work on this issue.
